# Setup
title:               Duho
tagline:             'A Jekyll theme'
description:         '여러가지 정리'
url:                 https://duhoro.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Duho Ro
  url:               https://duhoro.github.io
  email:             duho.ro@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
